### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by feeloow** [mattweber/elasticsearch-mocksolrplugin#4] opened 2012-08-31 10:37 UTC
When compiling with maven2 on Ubuntu 10.04.4 LTS server / java7 
I have the following compilation errors : 

$ sudo mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building elasticsearch-mocksolrplugin
[INFO]    task-segment: [package]
[INFO] ------------------------------------------------------------------------
[INFO] [enforcer:enforce {execution: enforce-maven}]
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Compiling 6 source files to /opt/elasticsearch-mocksolrplugin/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[86,24] error: cannot find symbol
[ERROR]  variable request of type RestRequest
/opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[118,88] error: cannot find symbol
[ERROR]  variable request of type RestRequest
/opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[168,72] error: cannot find symbol
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure

/opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[86,24] error: cannot find symbol
 variable request of type RestRequest
/opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[118,88] error: cannot find symbol
 variable request of type RestRequest
/opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[168,72] error: cannot find symbol

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19 seconds
[INFO] Finished at: Fri Aug 31 12:32:44 CEST 2012
[INFO] Final Memory: 25M/60M
[INFO] ------------------------------------------------------------------------

$ sudo mvn -e package
- Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] ------------------------------------------------------------------------
  [INFO] Building elasticsearch-mocksolrplugin
  [INFO]    task-segment: [package]
  [INFO] ------------------------------------------------------------------------
  [INFO] [enforcer:enforce {execution: enforce-maven}]
  [INFO] [resources:resources {execution: default-resources}]
  [INFO] Using 'UTF-8' encoding to copy filtered resources.
  [INFO] Copying 1 resource
  [INFO] [compiler:compile {execution: default-compile}]
  [INFO] Compiling 6 source files to /opt/elasticsearch-mocksolrplugin/target/classes
  [INFO] -------------------------------------------------------------
  [ERROR] COMPILATION ERROR : 
  [INFO] -------------------------------------------------------------
  [ERROR] /opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[86,24] error: cannot find symbol
  [ERROR]  variable request of type RestRequest
  /opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[118,88] error: cannot find symbol
  [ERROR]  variable request of type RestRequest
  /opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[168,72] error: cannot find symbol
  [INFO] 3 errors 
  [INFO] -------------------------------------------------------------
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD FAILURE
  [INFO] ------------------------------------------------------------------------
  [INFO] Compilation failure

/opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[86,24] error: cannot find symbol
 variable request of type RestRequest
/opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[118,88] error: cannot find symbol
 variable request of type RestRequest
/opt/elasticsearch-mocksolrplugin/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java:[168,72] error: cannot find symbol

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.BuildFailureException: Compilation failure
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:715)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
    at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:656)
    at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    ... 17 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19 seconds
[INFO] Finished at: Fri Aug 31 12:36:01 CEST 2012
[INFO] Final Memory: 25M/60M
[INFO] ------------------------------------------------------------------------

**Comment by juniorplenty** [comment] 2013-01-28 23:20
@feeloow did you get this to work?

**Comment by feeloow** [comment] 2013-01-29 08:29
No. I finally got back to native Solr.

**Comment by juniorplenty** [comment] 2013-02-25 20:34
Seems to be fixed in the latest version

**Comment by mattweber** [comment] 2013-02-25 20:38
I looked into this yesterday and was unable to reproduce (even with older versions).  I wonder if it was a problem when elasticsearch jars where not hosted in maven central.  At any rate, I am glad this is working for you now.

**Closed as completed by mattweber** 2013-02-25 20:38 UTC
